### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by kfrancis** [chargeover/chargeover_csharp#1]
Hey,

Any plans to release this on NuGet? I'd like to consume the library, but it's not easily usable without pushing it to NuGet. I can make those changes and send a pull req if you'd like ..

**Comment by consolibyte** [comment]
If you want to submit a pull request we'll gladly merge it in! That would be much appreciated!

**Comment by kfrancis** [comment]
Done :) Sorry about organizing it a little different. To get the library by itself, I needed to remove all that example code into it's own console project. I setup everything so that all you need to do (after merging, and making sure you have nuget.exe on the path) is run:

* msbuild ChargeOver.csproj
* nuget.exe setApiKey <your api key from nuget.org>
* nuget.exe pack ChargeOver.csproj -Symbols
* nuget.exe push <name of the output.nupkg>
