### ISSUE TITLE
Query Packages

### ISSUE THREAD

**Issue by kfrancis** [chargeover/chargeover_csharp#3]
There's no specific example for it, but how does one get a list of packages or get a package for a specific customer? I need to iterate through the customer/packages to get the start date, but I keep getting an empty 200 response.

**Comment by kfrancis** [comment]
@keith-chargeover ^^

**Comment by consolibyte** [comment]
You should be able to do this using the `.Find(...)` method. Do you know what your HTTP request/response looks like, or can you post the code you're using? 

I should be able to post an example in a bit as well.

**Comment by kfrancis** [comment]
The code looks like the following: 

````c#
api.Find(typeof(BillingPackage), new List<string>() { "customer_id:EQUALS:"+mycust.customer_id });
````

I do get a response (`200 OK`) but it has no content. I can easily iterate through the customers, but I also need to iterate through the billing/recurring packages of a customer in this project.

**Comment by keith-chargeover** [comment]
@kfrancis   Can you take a peek at the updated example, and see if this gets you what you need? 
https://github.com/chargeover/chargeover_csharp/blob/master/src/ChargeOver.Examples/ExamplePackages.cs#L48

Bunch of code has been updated to fix this. 

If you continue to have trouble, is there a way we can chat via gChat/Skype/something else and we can help you work through this? 

Quite obvious our C# libs need some love, so we're working through that too!

**Comment by kfrancis** [comment]
Looks better, thanks :)
